"""Function param descriptions: 
This function doesn't need params

This function has been executed for 1 times. Last execution:
1.Status: TriggerAcivatedSuccess
2.Input: 
[]

3.Output:
[{'json': {}}]
"""
def trigger_0(input_data):
  """
  comments: Trigger the workflow manually by user action.
  TODOs: 
    - Test the manual trigger to ensure workflow starts correctly.
  """
  params = {}
  function = transparent_trigger(integration="manualTrigger", resource="default", operation="default")
  output_data = function.run(input_data=None, params=params)
  return output_data



"""Function param descriptions: 
This function doesn't need params

This function has been executed for 1 times. Last execution:
1.Status: FunctionExecuteSuccess
2.Input: 
[{'json': {'messages': [{'role': 'system', 'content': 'You are a professional PostgreSQL SQL programmer, please only output a SQL string'}, {'role': 'user', 'content': "Please write a SQL query, which find how many columns are there in the table 'bloomberg_articles'"}]}}]

3.Output:
[{'json': {'choices': [{'text': "```sql\nSELECT COUNT(*) \nFROM information_schema.columns \nWHERE table_name = 'bloomberg_articles';\n```"}]}, 'pairedItem': {'item': 0}}]
"""
def action_0(input_data):
  """
  comments: Generate a SQL query string based on system and user prompts using AI completion.
  TODOs: 
    - Implement input messages array with system and user prompts.
    - Test AI completion output correctness.
  """
  params = {}
  function = transparent_action(integration="aiCompletion", resource="default", operation="default")
  output_data = function.run(input_data=input_data, params=params)
  return output_data



"""Function param descriptions: 
0 params["query"]: string = "", Required: Query. The SQL query to execute. You can use n8n expressions and $1, $2, $3, etc to refer to the 'Query Parameters' set in options below.(e.g. SELECT id, name FROM product WHERE quantity > $1 AND price <= $2). You can't use expression.
1 params["options"]: dict = {}: Options(Add Option) . properties description:
  ...hidden...

This function has been executed for 1 times. Last execution:
1.Status: FunctionExecuteSuccess
2.Input: 
[{'json': {'query': "SELECT COUNT(*) \nFROM information_schema.columns \nWHERE table_name = 'bloomberg_articles';"}}]

3.Output:
[{'json': {'count': '12'}, 'pairedItem': {'item': 0}}]
"""
def action_1(input_data):
  """
  comments: Execute the SQL query generated by AI in PostgreSQL database, setting 'query' and 'options' params properly from input_data without using expressions.
  TODOs: 
    - Implement params setting in action_1.
    - Test SQL execution and output format.
    - Handle possible errors.
  """
  params = {'options': {}, 'query': "SELECT COUNT(*) \nFROM information_schema.columns \nWHERE table_name = 'bloomberg_articles';"}
  function = transparent_action(integration="postgres", resource="database", operation="executeQuery")
  output_data = function.run(input_data=input_data, params=params)
  return output_data



"""Function param descriptions: 
0 params["select"]: enum[string] = "", Required: Send Message To(Select...) . Available values:
  0.0 value=="channel": Channel
  0.1 value=="user": User
1 params["channelId"]: dict{"mode":enum(str),"values":any} = {'mode': 'list', 'value': ''}, Required when (select in ['channel']), otherwise do not provide: Channel. The Slack channel to send to(Select a channel...) . "mode" should be one of ['id', 'name', 'url']: 
  1.0 params["channelId"]["value"](when "mode"="id"): string: By ID(C0122KQ70S7E)
  1.1 params["channelId"]["value"](when "mode"="name"): string: By Name(#general)
  1.2 params["channelId"]["value"](when "mode"="url"): string: By URL(https://app.slack.com/client/TS9594PZK/B0556F47Z3A)
2 params["user"]: dict{"mode":enum(str),"values":any} = {'mode': 'list', 'value': ''}, Activate(Not Required) when (select in ['user']), otherwise do not provide: User(Select a user...) . "mode" should be one of ['id', 'username']: 
  ...hidden...
3 params["messageType"]: enum[string] = "text": Message Type. Whether to send a simple text message, or use Slack’s Blocks UI builder for more sophisticated messages that include form fields, sections and more . Available values:
  3.0 value=="text": Simple Text Message. Supports basic Markdown
  3.1 value=="block": Blocks. Combine text, buttons, form elements, dividers and more in Slack 's visual builder
  3.2 value=="attachment": Attachments
4 params["text"]: string = "", Activate(Not Required) when (messageType in ['block']), otherwise do not provide: Notification Text. Fallback text to display in slack notifications. Supports <a href="https://api.slack.com/reference/surfaces/formatting">markdown</a> by default - this can be disabled in "Options".
5 params["blocksUi"]: string = "", Required when (messageType in ['block']), otherwise do not provide: Blocks. Enter the JSON output from Slack's visual Block Kit Builder here. You can then use expressions to add variable content to your blocks. To create blocks, use <a target='_blank' href='https://app.slack.com/block-kit-builder'>Slack's Block Kit Builder</a>
6 params["attachments"]: list[dict] = [{}], Activate(Not Required) when (messageType in ['attachment']), otherwise do not provide: Attachments(Add attachment item) . properties description:
  ...hidden...
7 params["otherOptions"]: dict = {}: Options. Other options to set(Add options) . properties description:
  ...hidden...

This function has been executed for 1 times. Last execution:
1.Status: FunctionExecuteSuccess
2.Input: 
[{'json': {'text': 'count: 12'}}]

3.Output:
[{'json': {'ok': True, 'channel': 'C09UW58R413', 'message': {'user': 'U09UT5PE4HZ', 'type': 'message', 'ts': '1765081717.622299', 'bot_id': 'B09V34LF560', 'app_id': 'A09UW3HDF37', 'text': 'count: 12', 'team': 'T09VCDJNALR', 'bot_profile': {'id': 'B09V34LF560', 'app_id': 'A09UW3HDF37', 'user_id': 'U09UT5PE4HZ', 'name': 'ProAgentBot', 'icons': {'image_36': 'https://a.slack-edge.com/80588/img/plugins/app/bot_36.png', 'image_48': 'https://a.slack-edge.com/80588/img/plugins/app/bot_48.png', 'image_72': 'https://a.slack-edge.com/80588/img/plugins/app/service_72.png'}, 'deleted': False, 'updated': 1764012858, 'team_id': 'T09VCDJNALR'}, 'blocks': [{'type': 'rich_text', 'block_id': '2DKG', 'elements': [{'type': 'rich_text_section', 'elements': [{'type': 'text', 'text': 'count: 12'}]}]}]}, 'message_timestamp': '1765081717.622299'}, 'pairedItem': {'item': 0}}]
"""
def action_2(input_data):
  """
  comments: Send the PostgreSQL query results to Slack channel 'general', setting required params for channel, message type, and text extraction.
  TODOs: 
    - Implement Slack params in action_2.
    - Test Slack message sending.
    - Handle possible errors.
  """
  params = { 'channelId': {'mode': 'name', 'value': 'general'},
             'messageType': 'text',
             'select': 'channel',
             'text': '={{$json["text"]}}'}
  function = transparent_action(integration="slack", resource="message", operation="post")
  output_data = function.run(input_data=input_data, params=params)
  return output_data



"""

This function has been executed for 1 times. Last execution:
1.Status: FunctionExecuteSuccess
2.Input: 
[{'json': {}}]

3.Output:
[{'json': {'ok': True, 'channel': 'C09UW58R413', 'message': {'user': 'U09UT5PE4HZ', 'type': 'message', 'ts': '1765081717.622299', 'bot_id': 'B09V34LF560', 'app_id': 'A09UW3HDF37', 'text': 'count: 12', 'team': 'T09VCDJNALR', 'bot_profile': {'id': 'B09V34LF560', 'app_id': 'A09UW3HDF37', 'user_id': 'U09UT5PE4HZ', 'name': 'ProAgentBot', 'icons': {'image_36': 'https://a.slack-edge.com/80588/img/plugins/app/bot_36.png', 'image_48': 'https://a.slack-edge.com/80588/img/plugins/app/bot_48.png', 'image_72': 'https://a.slack-edge.com/80588/img/plugins/app/service_72.png'}, 'deleted': False, 'updated': 1764012858, 'team_id': 'T09VCDJNALR'}, 'blocks': [{'type': 'rich_text', 'block_id': '2DKG', 'elements': [{'type': 'rich_text_section', 'elements': [{'type': 'text', 'text': 'count: 12'}]}]}]}, 'message_timestamp': '1765081717.622299'}, 'pairedItem': {'item': 0}}]
"""
def mainWorkflow(trigger_input: [{...}]):
    """
    comments: Main workflow to generate SQL query via AI, execute it in PostgreSQL, and send results to Slack.
    TODOs:
      - Build aiCompletion input messages with system and user prompts.
      - Extract and clean SQL query from AI output.
      - Execute query and format results for Slack.
    """
    # Step 1: Build AI input messages
    ai_input = [{
        "json": {
            "messages": [
                {"role": "system", "content": "You are a professional PostgreSQL SQL programmer, please only output a SQL string"},
                {"role": "user", "content": "Please write a SQL query, which find how many columns are there in the table 'bloomberg_articles'"}
            ]
        }
    }]

    # Step 2: Call aiCompletion action
    ai_output = action_0(ai_input)

    # Step 3: Extract and clean SQL query
    raw_query = ai_output[0]["json"]["choices"][0]["text"].strip()
    # Remove markdown code blocks if present
    if raw_query.startswith("```"):
        raw_query = raw_query.split("\n", 1)[1] if "\n" in raw_query else raw_query[3:]
        if raw_query.endswith("```"):
            raw_query = raw_query[:-3]
        raw_query = raw_query.strip()
    # Remove language identifiers like sql
    if raw_query.lower().startswith("sql"):
        raw_query = raw_query[3:].strip()

    # Step 4: Prepare input for PostgreSQL action
    pg_input = [{"json": {"query": raw_query}}]

    # Step 5: Execute the SQL query
    pg_output = action_1(pg_input)

    # Step 6: Format the PostgreSQL results for Slack
    slack_messages = []
    if len(pg_output) == 0:
        slack_messages.append({"json": {"text": "No results returned from the query."}})
    else:
        for row in pg_output:
            # Format each row as key: value pairs
            text_lines = []
            for key, value in row["json"].items():
                text_lines.append(f"{key}: {value}")
            text = "\n".join(text_lines)
            slack_messages.append({"json": {"text": text}})

    # Step 7: Send messages to Slack
    slack_output = action_2(slack_messages)

    return slack_output



"""

The directly running result for now codes with print results are as following:




You can also see the runnning result for all functions in there comments.
"""