"""Function param descriptions: 
This function doesn't need params

This function has been executed for 1 times. Last execution:
1.Status: TriggerAcivatedSuccess
2.Input: 
[]

3.Output:
[{'json': {}}]
"""
def trigger_0(input_data):
  """
  comments: Trigger the workflow manually by user clicking the button.
  TODOs: 
    - Test the manual trigger
    - Ensure it activates the main workflow
  """
  params = {}
  function = transparent_trigger(integration="manualTrigger", resource="default", operation="default")
  output_data = function.run(input_data=None, params=params)
  return output_data



"""Function param descriptions: 
This function doesn't need params

This function has been executed for 1 times. Last execution:
1.Status: FunctionExecuteSuccess
2.Input: 
[{'json': {'messages': [{'role': 'system', 'content': 'You are a professional PostgreSQL SQL programmer, please only output a SQL string'}, {'role': 'user', 'content': "Please write a SQL query, which use information schema to list column names, data types, and nullability in the table 'bloomberg_articles'"}]}}]

3.Output:
[{'json': {'choices': [{'text': "```sql\nSELECT \n    column_name, \n    data_type, \n    is_nullable\nFROM \n    information_schema.columns\nWHERE \n    table_name = 'bloomberg_articles';\n```"}]}, 'pairedItem': {'item': 0}}]
"""
def action_0(input_data):
  """
  comments: Use aiCompletion to generate SQL query from system and user prompts.
  TODOs: 
    - Implement the input messages array in mainWorkflow
    - Test aiCompletion output format
  """
  params = {}
  function = transparent_action(integration="aiCompletion", resource="default", operation="default")
  output_data = function.run(input_data=input_data, params=params)
  return output_data



"""Function param descriptions: 
0 params["query"]: string = "", Required: Query. The SQL query to execute. You can use n8n expressions and $1, $2, $3, etc to refer to the 'Query Parameters' set in options below.(e.g. SELECT id, name FROM product WHERE quantity > $1 AND price <= $2). You can't use expression.
1 params["options"]: dict = {}: Options(Add Option) . properties description:
  ...hidden...

This function has been executed for 1 times. Last execution:
1.Status: FunctionExecuteSuccess
2.Input: 
[{'json': {'query': "SELECT \n    column_name, \n    data_type, \n    is_nullable\nFROM \n    information_schema.columns\nWHERE \n    table_name = 'bloomberg_articles';"}}]

3.Output:
[{'json': {'column_name': 'id', 'data_type': 'bigint', 'is_nullable': 'NO'}, 'pairedItem': {'item': 0}}, {'json': {'column_name': 'published_at', 'data_type': 'timestamp without time zone', 'is_nullable': 'YES'}, 'pairedItem': {'item': 0}}, {'json': {'column_name': 'content_length', 'data_type': 'integer', 'is_nullable': 'YES'}, 'pairedItem': {'item': 0}}, {'json': {'column_name': 'export_date', 'data_type': 'timestamp without time zone', 'is_nullable': 'YES'}, 'pairedItem': {'item': 0}}, {'json': {'column_name': 'url', 'data_type': 'text', 'is_nullable': 'YES'}, 'pairedItem': {'item': 0}}, {'json': {'column_name': 'url_to_image', 'data_type': 'text', 'is_nullable': 'YES'}, 'pairedItem': {'item': 0}}, {'json': {'column_name': 'source_name', 'data_type': 'text', 'is_nullable': 'YES'}, 'pairedItem': {'item': 0}}, {'json': {'column_name': 'source_id', 'data_type': 'text', 'is_nullable': 'YES'}, 'pairedItem': {'item': 0}}, {'json': {'column_name': 'author', 'data_type': 'text', 'is_nullable': 'YES'}, 'pairedItem': {'item': 0}}, {'json': {'column_name': 'title', 'data_type': 'text', 'is_nullable': 'YES'}, 'pairedItem': {'item': 0}}, {'json': {'column_name': 'description', 'data_type': 'text', 'is_nullable': 'YES'}, 'pairedItem': {'item': 0}}, {'json': {'column_name': 'content', 'data_type': 'text', 'is_nullable': 'YES'}, 'pairedItem': {'item': 0}}]
"""
def action_1(input_data):
  """
  comments: Execute the SQL query generated by AI on PostgreSQL database with correct params.
  TODOs: 
    - Test query execution
    - Handle errors if query fails
  """
  params = { 'options': {},
             'query': 'SELECT column_name, data_type, is_nullable FROM information_schema.columns WHERE table_name = '
                      "'bloomberg_articles';"}
  function = transparent_action(integration="postgres", resource="database", operation="executeQuery")
  output_data = function.run(input_data=input_data, params=params)
  return output_data



"""Function param descriptions: 
0 params["select"]: enum[string] = "", Required: Send Message To(Select...) . Available values:
  0.0 value=="channel": Channel
  0.1 value=="user": User
1 params["channelId"]: dict{"mode":enum(str),"values":any} = {'mode': 'list', 'value': ''}, Required when (select in ['channel']), otherwise do not provide: Channel. The Slack channel to send to(Select a channel...) . "mode" should be one of ['id', 'name', 'url']: 
  1.0 params["channelId"]["value"](when "mode"="id"): string: By ID(C0122KQ70S7E)
  1.1 params["channelId"]["value"](when "mode"="name"): string: By Name(#general)
  1.2 params["channelId"]["value"](when "mode"="url"): string: By URL(https://app.slack.com/client/TS9594PZK/B0556F47Z3A)
2 params["user"]: dict{"mode":enum(str),"values":any} = {'mode': 'list', 'value': ''}, Activate(Not Required) when (select in ['user']), otherwise do not provide: User(Select a user...) . "mode" should be one of ['id', 'username']: 
  ...hidden...
3 params["messageType"]: enum[string] = "text": Message Type. Whether to send a simple text message, or use Slack’s Blocks UI builder for more sophisticated messages that include form fields, sections and more . Available values:
  3.0 value=="text": Simple Text Message. Supports basic Markdown
  3.1 value=="block": Blocks. Combine text, buttons, form elements, dividers and more in Slack 's visual builder
  3.2 value=="attachment": Attachments
4 params["text"]: string = "", Activate(Not Required) when (messageType in ['block']), otherwise do not provide: Notification Text. Fallback text to display in slack notifications. Supports <a href="https://api.slack.com/reference/surfaces/formatting">markdown</a> by default - this can be disabled in "Options".
5 params["blocksUi"]: string = "", Required when (messageType in ['block']), otherwise do not provide: Blocks. Enter the JSON output from Slack's visual Block Kit Builder here. You can then use expressions to add variable content to your blocks. To create blocks, use <a target='_blank' href='https://app.slack.com/block-kit-builder'>Slack's Block Kit Builder</a>
6 params["attachments"]: list[dict] = [{}], Activate(Not Required) when (messageType in ['attachment']), otherwise do not provide: Attachments(Add attachment item) . properties description:
  ...hidden...
7 params["otherOptions"]: dict = {}: Options. Other options to set(Add options) . properties description:
  ...hidden...

This function has been executed for 1 times. Last execution:
1.Status: FunctionExecuteSuccess
2.Input: 
[{'json': {'text': 'Columns info in bloomberg_articles table:\ncolumn_name | data_type | is_nullable\n-------------------------------------\nid | bigint | NO\npublished_at | timestamp without time zone | YES\ncontent_length | integer | YES\nexport_date | timestamp without time zone | YES\nurl | text | YES\nurl_to_image | text | YES\nsource_name | text | YES\nsource_id | text | YES\nauthor | text | YES\ntitle | text | YES\ndescription | text | YES\ncontent | text | YES'}}]

3.Output:
[{'json': {'ok': True, 'channel': 'C09UW58R413', 'message': {'user': 'U09UT5PE4HZ', 'type': 'message', 'ts': '1764967120.957409', 'bot_id': 'B09V34LF560', 'app_id': 'A09UW3HDF37', 'text': 'Columns info in bloomberg_articles table:\ncolumn_name | data_type | is_nullable\n-------------------------------------\nid | bigint | NO\npublished_at | timestamp without time zone | YES\ncontent_length | integer | YES\nexport_date | timestamp without time zone | YES\nurl | text | YES\nurl_to_image | text | YES\nsource_name | text | YES\nsource_id | text | YES\nauthor | text | YES\ntitle | text | YES\ndescription | text | YES\ncontent | text | YES', 'team': 'T09VCDJNALR', 'bot_profile': {'id': 'B09V34LF560', 'app_id': 'A09UW3HDF37', 'user_id': 'U09UT5PE4HZ', 'name': 'ProAgentBot', 'icons': {'image_36': 'https://a.slack-edge.com/80588/img/plugins/app/bot_36.png', 'image_48': 'https://a.slack-edge.com/80588/img/plugins/app/bot_48.png', 'image_72': 'https://a.slack-edge.com/80588/img/plugins/app/service_72.png'}, 'deleted': False, 'updated': 1764012858, 'team_id': 'T09VCDJNALR'}, 'blocks': [{'type': 'rich_text', 'block_id': 'tFs0', 'elements': [{'type': 'rich_text_section', 'elements': [{'type': 'text', 'text': 'Columns info in bloomberg_articles table:\ncolumn_name | data_type | is_nullable\n-------------------------------------\nid | bigint | NO\npublished_at | timestamp without time zone | YES\ncontent_length | integer | YES\nexport_date | timestamp without time zone | YES\nurl | text | YES\nurl_to_image | text | YES\nsource_name | text | YES\nsource_id | text | YES\nauthor | text | YES\ntitle | text | YES\ndescription | text | YES\ncontent | text | YES'}]}]}]}, 'message_timestamp': '1764967120.957409'}, 'pairedItem': {'item': 0}}]
"""
def action_2(input_data):
  """
  comments: Send the query result to Slack channel 'general' with correct params.
  TODOs: 
    - Test Slack message sending
    - Handle errors if Slack API fails
  """
  params = { 'channelId': {'mode': 'name', 'value': 'general'},
             'messageType': 'text',
             'select': 'channel',
             'text': '={{$json["text"]}}'}
  function = transparent_action(integration="slack", resource="message", operation="post")
  output_data = function.run(input_data=input_data, params=params)
  return output_data



"""

This function has been executed for 1 times. Last execution:
1.Status: FunctionExecuteSuccess
2.Input: 
[{'json': {}}]

3.Output:
[{'json': {'ok': True, 'channel': 'C09UW58R413', 'message': {'user': 'U09UT5PE4HZ', 'type': 'message', 'ts': '1764967120.957409', 'bot_id': 'B09V34LF560', 'app_id': 'A09UW3HDF37', 'text': 'Columns info in bloomberg_articles table:\ncolumn_name | data_type | is_nullable\n-------------------------------------\nid | bigint | NO\npublished_at | timestamp without time zone | YES\ncontent_length | integer | YES\nexport_date | timestamp without time zone | YES\nurl | text | YES\nurl_to_image | text | YES\nsource_name | text | YES\nsource_id | text | YES\nauthor | text | YES\ntitle | text | YES\ndescription | text | YES\ncontent | text | YES', 'team': 'T09VCDJNALR', 'bot_profile': {'id': 'B09V34LF560', 'app_id': 'A09UW3HDF37', 'user_id': 'U09UT5PE4HZ', 'name': 'ProAgentBot', 'icons': {'image_36': 'https://a.slack-edge.com/80588/img/plugins/app/bot_36.png', 'image_48': 'https://a.slack-edge.com/80588/img/plugins/app/bot_48.png', 'image_72': 'https://a.slack-edge.com/80588/img/plugins/app/service_72.png'}, 'deleted': False, 'updated': 1764012858, 'team_id': 'T09VCDJNALR'}, 'blocks': [{'type': 'rich_text', 'block_id': 'tFs0', 'elements': [{'type': 'rich_text_section', 'elements': [{'type': 'text', 'text': 'Columns info in bloomberg_articles table:\ncolumn_name | data_type | is_nullable\n-------------------------------------\nid | bigint | NO\npublished_at | timestamp without time zone | YES\ncontent_length | integer | YES\nexport_date | timestamp without time zone | YES\nurl | text | YES\nurl_to_image | text | YES\nsource_name | text | YES\nsource_id | text | YES\nauthor | text | YES\ntitle | text | YES\ndescription | text | YES\ncontent | text | YES'}]}]}]}, 'message_timestamp': '1764967120.957409'}, 'pairedItem': {'item': 0}}]
"""
def mainWorkflow(trigger_input: [{...}]):
    """
    comments: Main workflow to generate SQL query from AI, execute it on PostgreSQL, and send results to Slack.
    TODOs:
      - Build AI input messages
      - Clean AI output
      - Format PostgreSQL output for Slack
      - Test end-to-end
    """
    # Step 1: Build AI input messages
    ai_input = [{
        "json": {
            "messages": [
                {"role": "system", "content": "You are a professional PostgreSQL SQL programmer, please only output a SQL string"},
                {"role": "user", "content": "Please write a SQL query, which use information schema to list column names, data types, and nullability in the table 'bloomberg_articles'"}
            ]
        }
    }]

    # Step 2: Call aiCompletion action
    ai_output = action_0(ai_input)

    # Step 3: Extract and clean SQL query string
    ai_text = ai_output[0]['json']['choices'][0]['text'].strip()
    # Remove markdown if exists
    if ai_text.startswith('```'):
        # Remove code block markdown and language specifier
        lines = ai_text.split('\n')
        if lines[0].startswith('```'):
            lines = lines[1:]
        if lines[-1].strip() == '```':
            lines = lines[:-1]
        ai_text = '\n'.join(lines).strip()

    # Step 4: Prepare PostgreSQL input
    pg_input = [{"json": {"query": ai_text}}]

    # Step 5: Call PostgreSQL executeQuery action
    pg_output = action_1(pg_input)

    # Step 6: Extract rows from PostgreSQL output
    rows = pg_output

    # Step 7: Format rows into Slack message text
    if not rows:
        message_text = "No results returned from PostgreSQL query."
    else:
        lines = []
        # Extract column names from first row
        columns = rows[0]['json'].keys() if rows else []
        header = " | ".join(columns)
        lines.append(header)
        lines.append("-" * len(header))
        for row in rows:
            line = " | ".join(str(row['json'].get(col, '')) for col in columns)
            lines.append(line)
        message_text = "Columns info in bloomberg_articles table:\n" + "\n".join(lines)

    # Step 8: Prepare Slack input
    slack_input = [{"json": {"text": message_text}}]

    # Step 9: Call Slack post message action
    slack_output = action_2(slack_input)

    return slack_output



"""

The directly running result for now codes with print results are as following:




You can also see the runnning result for all functions in there comments.
"""